---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1":
    get:
      summary: projects
      tags:
      - projects
      security:
      - basicAuth: []
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
